version: '3.8'

services:
  streamlit:
    build: .
    container_name: sentiment-analysis-streamlit-new
    ports:
      - "8504:8501"
    volumes:
      - .:/app
    networks:
      ai-network:
        ipv4_address: "170.20.0.2"

networks:
  ai-network:
    external:
      name: ai-network
