version: '3.8'

services:
  streamlit_new:
    build: .
    container_name: sentiment-analysis-streamlit-new
    ports:
      - "8503:8501"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
